#!/usr/bin/env bun
/**
 * schema-gen — project internal zod schemas to explicit public types.
 *
 *   zod schema ──z.toJSONSchema──▶ JSON Schema ──json-schema-to-typescript──▶ explicit .ts
 *
 * Author the schema in src/schemas.ts (internal); this emits the explicit type
 * into src/types.generated.ts (committed, re-exported by the index). Keeping the
 * raw zod type out of the public API is what lets the package pass JSR
 * fast-types. See ../../.github-private/docs/schema-types-strategy.md.
 *
 *   bun run schema:gen     # write src/types.generated.ts
 *   bun run schema:check   # exit 1 if the committed file is stale (CI drift gate)
 *
 * Generalizes to a shared @bounded-systems/schema-gen; the schema→type-name
 * manifest below is the only per-package input.
 */
import { z } from "zod";
import { compile } from "json-schema-to-typescript";

import { auditEntrySchema } from "../src/schemas.ts";

// Manifest: each internal schema → its public type name.
const SCHEMAS: Array<[z.ZodType, string]> = [[auditEntrySchema, "RateLimitAuditEntry"]];

const CHECK = process.argv.includes("--check");
const OUT = new URL("../src/types.generated.ts", import.meta.url).pathname;

// Optional props become `?: T | undefined` so the type is sound under
// `exactOptionalPropertyTypes` (which treats `?: T` and `T | undefined` as
// distinct). Matches what `z.infer` produces.
const exactOptional = (ts: string): string =>
  ts.replace(/^(\s+[\w"']+\?: )(.+);$/gm, (_m, head, type) =>
    type.includes("| undefined") ? `${head}${type};` : `${head}${type} | undefined;`,
  );

let body = "";
for (const [schema, name] of SCHEMAS) {
  const js = z.toJSONSchema(schema, { target: "draft-7" }) as Record<string, unknown>;
  body += exactOptional((await compile(js, name, { bannerComment: "", additionalProperties: false })).trim()) + "\n\n";
}
const content =
  "// @generated by scripts/gen-schema-types.ts — DO NOT EDIT.\n" +
  "// Author the schema in src/schemas.ts, then run `bun run schema:gen`.\n\n" +
  body;

if (CHECK) {
  const cur = await Bun.file(OUT)
    .text()
    .catch(() => "");
  if (cur.trim() !== content.trim()) {
    console.error("::error::src/types.generated.ts is stale — run `bun run schema:gen` and commit.");
    process.exit(1);
  }
  console.log("types.generated.ts up to date.");
  process.exit(0);
}
await Bun.write(OUT, content);
console.log(`wrote src/types.generated.ts (${SCHEMAS.length} type(s))`);
