// @generated by @bounded-systems/schema-gen — DO NOT EDIT.
// Author the schema (with .describe()) and run your `schema:gen` script.

/**
 * One parsed `rate-limit.jsonl` audit row: the gh call, its bucket cost, and GH-1533 attribution.
 */
export interface RateLimitAuditEntry {
  /**
   * ISO-8601 timestamp the row was written.
   */
  ts: string;
  /**
   * The gh argv that produced the row.
   */
  argv: string[];
  /**
   * The rate-limit bucket the call drew from.
   */
  bucket: "core" | "graphql" | "search";
  /**
   * Bucket points remaining before the call.
   */
  remaining_before: number | null;
  /**
   * Bucket points remaining after the call.
   */
  remaining_after: number | null;
  /**
   * The gh process exit code.
   */
  exit_code: number;
  /**
   * Why the gated call threw, or null.
   */
  threw: ("BUDGET_EXHAUSTED" | "RUNTIME_ERROR") | null;
  /**
   * Cache-derived cost estimate kept for estimateSweepCost.
   */
  cost_delta: number | null;
  /**
   * graphql (incl. --json) or rest; null when not derivable.
   */
  api?: "graphql" | "rest" | undefined;
  /**
   * prx verb that issued the call; null outside runCli.
   */
  verb?: string | null | undefined;
  /**
   * Process identity (claude-code, a test harness, …).
   */
  actor?: string | undefined;
  /**
   * GraphQL/REST operation name; null when not derivable.
   */
  operation?: string | null | undefined;
  /**
   * Exact/measured GraphQL cost, else null.
   */
  cost?: number | null | undefined;
  /**
   * Bucket points remaining after the call.
   */
  remaining?: number | null | undefined;
  /**
   * The bucket's point limit.
   */
  limit?: number | null | undefined;
  /**
   * Bucket reset time, ISO-8601.
   */
  reset_at?: string | null | undefined;
  /**
   * Wall time in the gh spawn (0 for a gated-out call).
   */
  duration_ms?: number | undefined;
  /**
   * Why a residual gh call is load-bearing (GH-1602); null when incidental.
   */
  gh_truth_reason?: ("forward-orphan-detection" | "drift-comparator" | "stale-comparator") | null | undefined;
}

